### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable in /home/travis/build/aliyun/php-kms-sdk/vendor/phpunit/php-code-coverage/src/Report/Html/Renderer/File.php on line 307

### ISSUE THREAD

**Issue by talentant** [aliyun/php-kms-sdk#6]
PHP 7.2 出现大量 Warning

https://travis-ci.org/aliyun/php-kms-sdk/jobs/482756659

**Comment by ghost** [comment]
> PHP 7.2 出现大量 Warning
> 
> https://travis-ci.org/aliyun/php-kms-sdk/jobs/482756659

感谢关心和建议，这是在渲染html版本的覆盖率出现的phpunit问题，可忽略，但我们即将提交的更新不再在ci下生成html覆盖率。

**Comment by talentant** [comment]
明白了
